# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ab5d9aeddc5960d7558cf67d2b7317be8c9f2ac7ef28d5ca2ed3f1232677715b815ba62b96cfed22d3cb9a5dd07579e9db57cce17b60b8dd0bb9f1c54f6ac1

test:
  secret_key_base: 4742f92777afc06ce216999499e10391a34034e32d1fca5f552fb83dc2bebcdd2c0878d76aa427ff8599f955accf3361539ef1b2e94fcd45df81e9f4a064231d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
